apiVersion: v1
kind: Namespace
metadata:
  name: kong
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: kong
  labels:
    app: kong
data:
  KONG_DATABASE: postgres
  KONG_PG_DATABASE: kong
  KONG_PG_HOST: postgres
  KONG_PG_USER: kong
  KONG_PG_PASSWORD: kong
  KONG_PG_PORT: "5432"